runtime: python37
service: your_project
instance_class: B1
handlers:
       - url: /.*
         script: auto
basic_scaling:
   max_instances: 1
   idle_timeout: 10m
env_variables:
   GOOGLE_APPLICATION_CREDENTIALS: "D:\\certs\\RIU_demo-PRE.json"