runtime: python38
service: <your_instance>
instance_class: B2
handlers:
  - url: /.*
    script: auto
entrypoint: gunicorn -b :$PORT <your_package>.main:app #Complete with the package where the main.py is
basic_scaling:
  max_instances: 1
  idle_timeout: 10m