runtime: custom
service: <your_instance>
env: flex
network:
  forwarded_ports:
    - 80:8080
handlers:
    - url: /.*
      script: auto
automatic_scaling:
   min_num_instances: 1
   max_num_instances: 1